import { ReactNode, useState, useEffect } from 'react';
import { getLocale, setLocale, Locale, LOCALES } from '../lib/i18n';
const NAV = [{href:'/',label:'Home'},{href:'/agent',label:'Agent'},{href:'/pricing',label:'Pricing'},{href:'/book',label:'Book Service'},{href:'/about',label:'About'}];
export default function Layout({children}:{children:ReactNode}){
const [user,setUser]=useState<any>(null);
const [country,setCountry]=useState('AU');
const [lang,setLang]=useState<Locale>('en');
useEffect(()=>{const s=localStorage.getItem('ph_user');if(s)try{setUser(JSON.parse(s))}catch{} const c=localStorage.getItem('ph_country');if(c)setCountry(c);setLang(getLocale());},[]);
const hCountry=(c:string)=>{setCountry(c);localStorage.setItem('ph_country',c);window.location.reload()};
const hLang=(l:string)=>{setLocale(l as Locale);setLang(l as Locale);window.location.reload()};
const hOut=()=>{localStorage.removeItem('ph_user');localStorage.removeItem('ph_token');window.location.href='/auth/signin'};
const ss:any={fontSize:'.84rem',padding:'8px 34px 8px 12px',borderRadius:8,border:'none',background:'white',color:'#1e3a5f',fontWeight:600,cursor:'pointer',outline:'none',boxShadow:'0 2px 6px rgba(0,0,0,.15)',appearance:'none',WebkitAppearance:'none',backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='7'%3E%3Cpath d='M0 0l6 7 6-7z' fill='%236b7280'/%3E%3C/svg%3E\")",backgroundRepeat:'no-repeat',backgroundPosition:'right 11px center',minWidth:155};
return(<div style={{minHeight:'100vh',display:'flex',flexDirection:'column',fontFamily:'-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif'}}>
<header style={{background:'linear-gradient(135deg,#1e3a5f 0%,#2d5a8e 100%)',padding:'0 20px',borderBottom:'3px solid #059669',position:'sticky',top:0,zIndex:1000}}>
<div style={{maxWidth:1200,margin:'0 auto',display:'flex',alignItems:'center',justifyContent:'space-between',height:62}}>
<a href="/" style={{display:'flex',alignItems:'center',gap:8,textDecoration:'none'}}><span style={{fontSize:'1.4rem'}}>📒</span><span style={{fontSize:'1.1rem',fontWeight:700,color:'white'}}>PH<span style={{color:'#4ade80'}}>Ledger</span></span></a>
<nav style={{display:'flex',alignItems:'center',gap:4}}>{NAV.map(l=><a key={l.href} href={l.href} style={{fontSize:'.82rem',color:'rgba(255,255,255,.9)',textDecoration:'none',padding:'6px 12px',borderRadius:6}}>{l.label}</a>)}</nav>
<div style={{display:'flex',alignItems:'center',gap:12}}>
<select value={country} onChange={e=>hCountry(e.target.value)} style={ss}><option value="AU">🇦🇺 Australia</option><option value="CA">🇨🇦 Canada</option></select>
<select value={lang} onChange={e=>hLang(e.target.value)} style={{...ss,minWidth:145}}><option value="en">🇬🇧 English</option><option value="zh-CN">🇨🇳 简体中文</option><option value="zh-TW">🇹🇼 繁體中文</option><option value="ja">🇯🇵 日本語</option><option value="ko">🇰🇷 한국어</option><option value="es">🇪🇸 Español</option><option value="fr">🇫🇷 Français</option></select>
<span style={{width:1,height:24,background:'rgba(255,255,255,.25)'}}/>
{user?(<div style={{display:'flex',alignItems:'center',gap:8}}>{user.role==='admin'&&<a href="/admin" style={{fontSize:'.7rem',padding:'3px 8px',background:'#fef3c7',borderRadius:4,color:'#92400e',fontWeight:600,textDecoration:'none'}}>ADMIN</a>}<span style={{fontSize:'.74rem',color:'rgba(255,255,255,.7)',maxWidth:120,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{user.email}</span><button onClick={hOut} style={{fontSize:'.74rem',padding:'6px 12px',border:'none',borderRadius:6,background:'rgba(255,255,255,.15)',color:'white',cursor:'pointer'}}>Sign Out</button></div>):(<div style={{display:'flex',alignItems:'center',gap:6}}><a href="/auth/signin" style={{fontSize:'.82rem',color:'white',textDecoration:'none',padding:'6px 12px'}}>Sign In</a><a href="/auth/signup" style={{fontSize:'.82rem',padding:'7px 16px',background:'#059669',color:'white',borderRadius:6,textDecoration:'none',fontWeight:600}}>Sign Up</a></div>)}
</div></div></header>
<main style={{flex:1,background:'#f8fafc'}}>{children}</main>
<footer style={{background:'#1e293b',color:'rgba(255,255,255,.7)',padding:'32px 24px 20px',borderTop:'3px solid #059669'}}><div style={{maxWidth:1200,margin:'0 auto'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:24,marginBottom:24}}><div><div style={{fontSize:'1rem',fontWeight:700,color:'white',marginBottom:8}}>📒 PH<span style={{color:'#4ade80'}}>Ledger</span></div><p style={{fontSize:'.72rem',lineHeight:1.6,margin:0,color:'rgba(255,255,255,.5)'}}>Intelligent Finance<br/>AU & CA</p></div><div><div style={{fontSize:'.7rem',fontWeight:600,color:'rgba(255,255,255,.4)',textTransform:'uppercase',marginBottom:8}}>Platform</div>{[{h:'/agent',l:'Finance Agent'},{h:'/book',l:'Book Service'},{h:'/pricing',l:'Pricing'}].map(x=><a key={x.h} href={x.h} style={{display:'block',fontSize:'.75rem',color:'rgba(255,255,255,.65)',textDecoration:'none',marginBottom:4}}>{x.l}</a>)}</div><div><div style={{fontSize:'.7rem',fontWeight:600,color:'rgba(255,255,255,.4)',textTransform:'uppercase',marginBottom:8}}>Company</div>{[{h:'/about',l:'About'},{h:'/feedback',l:'Feedback'}].map(x=><a key={x.h} href={x.h} style={{display:'block',fontSize:'.75rem',color:'rgba(255,255,255,.65)',textDecoration:'none',marginBottom:4}}>{x.l}</a>)}</div><div><div style={{fontSize:'.7rem',fontWeight:600,color:'rgba(255,255,255,.4)',textTransform:'uppercase',marginBottom:8}}>Account</div>{[{h:'/auth/signin',l:'Sign In'},{h:'/auth/signup',l:'Sign Up'}].map(x=><a key={x.h} href={x.h} style={{display:'block',fontSize:'.75rem',color:'rgba(255,255,255,.65)',textDecoration:'none',marginBottom:4}}>{x.l}</a>)}</div></div><div style={{borderTop:'1px solid rgba(255,255,255,.1)',paddingTop:14,fontSize:'.65rem',color:'rgba(255,255,255,.3)'}}>© 2026 PHLedger Pty Ltd. 🇦🇺 PayTo NPP · 🇨🇦 Interac</div></div></footer></div>);}
